name: Hiroki Kumamoto's page
markdown: redcarpet
redcarpet:
    extensions: [tables,autolink,strikethrough]
highlighter: pygments
paginate: 8
description: Hiroki Kumamoto's page
intro: Hiroki Kumamoto's page
disqus_shortname: kumabook
port: 2000

exclude: ["Gemfile", "Gemfile.lock", ".gitignore"]
permalink: /:year/:i_month/:i_day/:title.html

ga_tracking_id: UA-63569468-1
