name: Keep Tryin'!  Keep Seachin'!
markdown: redcarpet
redcarpet:
    extensions: [tables,autolink,strikethrough]
highlighter: pygments
paginate: 8
description: hiroki kumamoto's diary
intro: Keep Tryin'!  Keep Seachin'!
disqus_shortname: kumabook
port: 2000

twitter_username: kumabook
github_username:  kumabook
exclude: ["Gemfile", "Gemfile.lock", ".gitignore"]
permalink: /:year/:i_month/:i_day/:title.html

ga_tracking_id: UA-63569468-1
