name: go beyond my wish
markdown: redcarpet
redcarpet:
    extensions: [tables,autolink,strikethrough]
highlighter: pygments
paginate: 8
description: go beyond my wish
intro: go beyond my wish
disqus_shortname: kumabook
port: 2000

twitter_username: kumabook
github_username:  kumabook
exclude: ["Gemfile", "Gemfile.lock", ".gitignore"]
permalink: /:year/:i_month/:i_day/:title.html

ga_tracking_id: UA-63569468-1
